### ISSUE TITLE
matrix has no inverse (bug in handling of 1-periodic graphs)

### ISSUE THREAD

**Issue by paulneves77** [odf/gavrog#14]
Hi, I've been running a lot of automatically generated crystal nets through Systre (great program!), and I have run into some errors. I have included a graph that will reproduce this bug when run in Systre. Note also that it’s possible there is something wrong with my input graph.

The error printed to the .out file is:
```
==================================================
!!! ERROR (INTERNAL) - Unexpected java.lang.ArithmeticException: matrix has no inverse
!!!    In structure #1 - "mp-1219151_Ga_0".
!!!    Last status: Computing the unique invariant (a.k.a. Systre key) for this net...
!!!    Stack trace:
!!!       java.lang.ArithmeticException: matrix has no inverse
!!!       	at org.gavrog.jane.compounds.Matrix.inverse(Matrix.java:748)
!!!       	at org.gavrog.joss.pgraphs.basic.PeriodicGraph.invariant(PeriodicGraph.java:1885)
!!!       	at org.gavrog.joss.pgraphs.basic.PeriodicGraph.getSystreKey(PeriodicGraph.java:2089)
!!!       	at org.gavrog.apps.systre.SystreCmdline.processGraph(SystreCmdline.java:280)
!!!       	at org.gavrog.apps.systre.SystreCmdline.processDisconnectedGraph(SystreCmdline.java:676)
!!!       	at org.gavrog.apps.systre.SystreCmdline.processGraph(SystreCmdline.java:194)
!!!       	at org.gavrog.apps.systre.SystreCmdline.processDataFile(SystreCmdline.java:921)
!!!       	at org.gavrog.apps.systre.SystreCmdline.run(SystreCmdline.java:1120)
!!!       	at org.gavrog.apps.systre.SystreCmdline.main(SystreCmdline.java:1135)
==================================================
```

The graph that reproduces this error is:
```
PERIODIC_GRAPH
ID mp-1219151_Ga_0
EDGES
  1 5 0 0 0
  1 5 1 0 0
  3 5 0 0 0
END
```

**Comment by odf** [comment]
Same bug as #13, now fixed.
